name: gits_logtime
description: A sample command-line application.
version: 0.3.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dcli: ^1.34.0
  args: ^2.3.1
  path: ^1.8.2
  collection: ^1.16.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6

executables:
  gits-logtime: gits_logtime
